---
- name: use command to do things 
  hosts: all 
  user: ansible
  become: true

  tasks:
  - name: get coreutils version
    block:
      command: "{{ item }}"
      with_items:
        - rpm -q coreutils
        - yum install -y python3
