---
- name: use command to do things 
  hosts: all 
  user: ansible
  become: true
  
  tasks: 
    - name: get coreutils version and install pip
      commmand: "{{ item }}"
      with_items:
        - rpm -q coreutils
